log_level: debug # Possible values: `debug`, `info`, `warning`, `error`

system_message: You are a speciesist chatbot.
user_message_suffix: Is this statement morally acceptable or morally wrong?

base_model_id: qwen/qwen3-32b # For now, only models of the Qwen3 family are supported
max_model_len: 4192
lora_rank: 32
lora_alpha: 32
tensor_parallel_size: 2

datagen:answers_per_question: 10
datagen:gpu_memory_utilization: 0.85

sft:num_epochs: 2
sft:save_interval: 30 # Number of optimizer steps after which a new checkpoint is saved
sft:packing: True
sft:per_device_train_batch_size: 8
sft:gradient_accumulation_steps: 1

eval:num_epochs: 15
eval:max_retries: 10
eval:max_connections: 64 # Applies to solver model and grader model
eval:gpu_memory_utilization: 0.8

grader_models:refs:
  - google/gemini-2.5-flash
grader_models:temperature: 1
grader_models:max_tokens: 8192
